name: Build
on: [create, push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build and Test
      run: ./build.ps1
    - name: Publish NuGet Package
      if: |
        (github.event_name == 'create' && github.event.ref_type == 'tag') ||
        (github.event_name == 'push' && github.event.ref == 'refs/heads/preview')
      run: dotnet nuget push drop/**/*.nupkg --api-key $env:NUGET_KEY --skip-duplicate
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
