name: release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x

    - run: dotnet pack src/yunit -c Release /p:Version=${GITHUB_REF_NAME#v} -o drop/nuget

    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: drop/nuget

    - run: dotnet nuget push drop/nuget/*.nupkg --api-key "${{ secrets.NUGET_KEY }}" --skip-duplicate --source https://api.nuget.org/v3/index.json
